# bm-syntax ZLE integration shim
# Sources: Loads the bm-syntax highlighter as a ZLE hook
#
# Integration mode: External process
# The bm-syntax binary parses BUFFER and outputs region_highlight entries.
# This is the portable approach. Native zmodload integration is Phase 4b.
#
# Usage: source this file in .zshrc (after compinit, before prompt)

# Path to bm-syntax binary (set by Nix or discovered on PATH)
: ${BM_SYNTAX_BIN:=$(command -v bm-syntax 2>/dev/null)}

# Skip if binary not found
if [[ -z "$BM_SYNTAX_BIN" ]] || [[ ! -x "$BM_SYNTAX_BIN" ]]; then
  return 0
fi

# Theme file (generated by bm-shell-engine or provided directly)
: ${BM_SYNTAX_THEME:=${XDG_CONFIG_HOME:-$HOME/.config}/bm-syntax/theme.yaml}

_bm_syntax_highlight() {
  # Only highlight if we have content
  [[ -z "$BUFFER" ]] && return

  # Call bm-syntax to get region_highlight entries
  # Format: one "start end fg=#RRGGBB" per line
  local output
  output=$("$BM_SYNTAX_BIN" highlight --buffer "$BUFFER" 2>/dev/null)

  # Clear previous highlights and apply new ones
  region_highlight=()
  local line
  while IFS= read -r line; do
    [[ -n "$line" ]] && region_highlight+=("$line")
  done <<< "$output"
}

# Register as ZLE hook — fires on every line redraw
autoload -Uz add-zle-hook-widget
add-zle-hook-widget line-pre-redraw _bm_syntax_highlight
